sudo: required
services:
  - docker


before_install:
  - docker build -t sagarbiswas012/docker-react -f Dockerfile.dev .

script:
  - docker run sagarbiswas012/docker-react npm run test -- --coverage